/*
 Navicat Premium Data Transfer

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 50719
 Source Host           : localhost:3306
 Source Schema         : enroll

 Target Server Type    : MySQL
 Target Server Version : 50719
 File Encoding         : 65001

 Date: 05/10/2021 16:21:04
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for student
-- ----------------------------
DROP TABLE IF EXISTS `student`;
CREATE TABLE `student`  (
  `username` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '名字',
  `specialty` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '专业',
  `time` timestamp NULL DEFAULT NULL COMMENT '报道时间',
  `count` int(11) NULL DEFAULT NULL COMMENT '第几个打卡'
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of student
-- ----------------------------
INSERT INTO `student` VALUES ('王奕文', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('左蕴秋', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('严阳', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('周奕炜', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('郑雯', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('谢秀秀', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王洵孜', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王灏', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘克旭', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘濮玮', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李繁', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('沈俊楠', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张升远', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张家硕', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('陈韬', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('季熙来', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('冼星晓', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('钱松浩', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('朱晓楠', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李可心', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('周艳婷', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('徐董慧', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('傅莞渊', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王秋雨', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王超逸', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('石毅', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('阮定邦', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('沈非凡', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张浩皖', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('范超', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('钟卓荣', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王若霖', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('涂娟', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('憨芳静', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('马金武', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('杨滢鉴', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('应章隆', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张天乙', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('黄锐', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('康喜', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('赖玉轩', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王莹莹', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('朱羽', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张思懿', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('孟文丽', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('姚依辰', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('许泽阳', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('季星宇', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('黄宏进', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('梅雨涛', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('薄翔文', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('陈雪钦', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王铭璋', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('付佩铖', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('吴思源', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('汪春瑶', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('陈杭', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('陈鹏', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('姜乐天', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('徐一鸣', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('蒋序林', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('路超', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('滕俊辰', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('马静', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('令乐乐', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('林雨菲', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('魏嘉怡', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('马宇', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王爽', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('庄克伟', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('杨锐韬', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('陈嘉春', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('赵崇睿', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('咸浩恒', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('喻梓轩', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('谭振龙', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('赖品来', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('肖灵', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('吴晨', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张乐妍', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('黄雨彤', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('马沁辉', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('邓建', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('卢松佳', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('吉鹏宇', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李予宁', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('吴欣航', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('邱毓诚', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('宋东贤', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张嘉祥', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('姜天浩', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('谢俊杰', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王男', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张朝玉', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('陈济韬', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('夏圣宝', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('郭飞扬', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('曾之傲', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('曲凯霞', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('仲婧彬', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('闫雪', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张菁菁', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('韩承希', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘靖宇', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('杨逸岚', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张德贤', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('罗钰', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('周胜', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('孟庆霖', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('黄沛然', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('田羽菲', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李承霖', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('陆盈竹', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('薛清瑶', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王振清', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('孔德浩', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('田明轩', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('岑郅烜', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('沈琳翔', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张宸宇', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('周涛', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('赵曜', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('曾华扬', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王钰露', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('葛杭琦', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('马文超', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('马洋斌', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('朱凯', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘柏均', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘烔楷', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李佳明', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('林梓杭', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('柯占林', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('黄骏骁', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘芮希', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张惜如', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('马子超', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('叶泰成', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('朱廷峰', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李冉', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张宇飏', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('林康', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('周潇', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('姜富标', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('高卓文', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('董瑞阳', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张华', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王晓婧', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('尹相茹', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('代卓凡', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘翀', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('吴宏健', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('孔羽桐', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李静怡', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('邹妍妍', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('苗瑞麟', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('孟晓', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('莫书迪', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('田立新', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('孙振宇', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('胡顺超', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘璐', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('罗小雪', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李仁怀', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('杨欣睿', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('杨程', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('马兰慧', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李沂晋', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('龚杰', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李婷', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('吴玉', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('何璇', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘天文', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李瑞丰', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('吴嘉伟', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('宋磊', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张尧', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('岳毅', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张仁迅', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('季筱涵', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王宣迪', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王浩', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('朱天祥', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('杨兴浩', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('何芷锌', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('宋心怡', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王怡欣', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('朱灵超', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('徐文迪', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王之骄', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('冯佳楠', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张剑琳', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('山宇锐', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王硕', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('卞宇杰', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('杨光辉', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('郑明宇', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王宇娇', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李忠蔚', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('辛政阳', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('潘子航', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('沈舒畅', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('谢家明', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('韩书星', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('程明璐', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('陆钊瑞', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李尔瀚', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王争', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('毛崴', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘俊杰', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李翔羽', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('陈浪', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张佳丽', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王雨豪', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('朱王令', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('石桑俐', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('孙思姣', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('柏泉', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('胡鹏飞', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('仇扬', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('姜斌', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('葛彪', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('邵如梦', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('丁田中', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('伍尚根', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('闵玥', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张帅帅', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('潘飞', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('石晓彬', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王梦琴', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('宋沁心', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('向宇月', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('吴欢华', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('周焱', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李勇德', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘项杰', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘派', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘宵宇', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('马赛', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('陈小朋', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('徐剑瑜', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张会兴', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('陈威', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('姚璨', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('钱灿辉', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李锦添', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('毕欣', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('陈一楠', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('曹德亮', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张志', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('常世琦', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('陈亨', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张学妹', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('牛兵', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('蒋珊珊', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王心雨', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('顾彦', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('计逸宁', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('李智彬', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('詹进飞', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张荣祯', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张延欣', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('黄德伟', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('贾婧冰', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张美苑', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('戴莹莹', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('法安琪', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('黄可言', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王欣', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('俞周强', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张韵风', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('曾翔', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('孙静', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张仁杰', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张哲', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('杜智颜', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('冯晨晨', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王海燕', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王欣茹', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('邹观哲', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('高飞', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('孟琪', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('孙甘露', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('谢慧慧', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘玟', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('殷秀秀', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张琳静', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('张诗韵', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('黄丽霞', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('秦秀', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('姚希颖', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('尤浩杰', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('刘南君', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('王宪玥', NULL, NULL, NULL);
INSERT INTO `student` VALUES ('曾辉', NULL, NULL, NULL);

SET FOREIGN_KEY_CHECKS = 1;
