/*
 Navicat Premium Data Transfer

 Source Server         : localhost_3306
 Source Server Type    : MySQL
 Source Server Version : 50719
 Source Host           : localhost:3306
 Source Schema         : enroll

 Target Server Type    : MySQL
 Target Server Version : 50719
 File Encoding         : 65001

 Date: 05/10/2021 16:21:20
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for student_image
-- ----------------------------
DROP TABLE IF EXISTS `student_image`;
CREATE TABLE `student_image`  (
  `username` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '名字',
  `image` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '图片'
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

-- ----------------------------
-- Records of student_image
-- ----------------------------
INSERT INTO `student_image` VALUES ('王奕文', NULL);
INSERT INTO `student_image` VALUES ('左蕴秋', NULL);
INSERT INTO `student_image` VALUES ('严阳', NULL);
INSERT INTO `student_image` VALUES ('周奕炜', NULL);
INSERT INTO `student_image` VALUES ('郑雯', NULL);
INSERT INTO `student_image` VALUES ('谢秀秀', NULL);
INSERT INTO `student_image` VALUES ('王洵孜', NULL);
INSERT INTO `student_image` VALUES ('王灏', NULL);
INSERT INTO `student_image` VALUES ('刘克旭', NULL);
INSERT INTO `student_image` VALUES ('刘濮玮', NULL);
INSERT INTO `student_image` VALUES ('李繁', NULL);
INSERT INTO `student_image` VALUES ('沈俊楠', NULL);
INSERT INTO `student_image` VALUES ('张升远', NULL);
INSERT INTO `student_image` VALUES ('张家硕', NULL);
INSERT INTO `student_image` VALUES ('陈韬', NULL);
INSERT INTO `student_image` VALUES ('季熙来', NULL);
INSERT INTO `student_image` VALUES ('冼星晓', NULL);
INSERT INTO `student_image` VALUES ('钱松浩', NULL);
INSERT INTO `student_image` VALUES ('朱晓楠', NULL);
INSERT INTO `student_image` VALUES ('李可心', NULL);
INSERT INTO `student_image` VALUES ('周艳婷', NULL);
INSERT INTO `student_image` VALUES ('徐董慧', NULL);
INSERT INTO `student_image` VALUES ('傅莞渊', NULL);
INSERT INTO `student_image` VALUES ('王秋雨', NULL);
INSERT INTO `student_image` VALUES ('王超逸', NULL);
INSERT INTO `student_image` VALUES ('石毅', NULL);
INSERT INTO `student_image` VALUES ('阮定邦', NULL);
INSERT INTO `student_image` VALUES ('沈非凡', NULL);
INSERT INTO `student_image` VALUES ('张浩皖', NULL);
INSERT INTO `student_image` VALUES ('范超', NULL);
INSERT INTO `student_image` VALUES ('钟卓荣', NULL);
INSERT INTO `student_image` VALUES ('王若霖', NULL);
INSERT INTO `student_image` VALUES ('涂娟', NULL);
INSERT INTO `student_image` VALUES ('憨芳静', NULL);
INSERT INTO `student_image` VALUES ('马金武', NULL);
INSERT INTO `student_image` VALUES ('杨滢鉴', NULL);
INSERT INTO `student_image` VALUES ('应章隆', NULL);
INSERT INTO `student_image` VALUES ('张天乙', NULL);
INSERT INTO `student_image` VALUES ('黄锐', NULL);
INSERT INTO `student_image` VALUES ('康喜', NULL);
INSERT INTO `student_image` VALUES ('赖玉轩', NULL);
INSERT INTO `student_image` VALUES ('王莹莹', NULL);
INSERT INTO `student_image` VALUES ('朱羽', NULL);
INSERT INTO `student_image` VALUES ('张思懿', NULL);
INSERT INTO `student_image` VALUES ('孟文丽', NULL);
INSERT INTO `student_image` VALUES ('姚依辰', NULL);
INSERT INTO `student_image` VALUES ('许泽阳', NULL);
INSERT INTO `student_image` VALUES ('季星宇', NULL);
INSERT INTO `student_image` VALUES ('黄宏进', NULL);
INSERT INTO `student_image` VALUES ('梅雨涛', NULL);
INSERT INTO `student_image` VALUES ('薄翔文', NULL);
INSERT INTO `student_image` VALUES ('陈雪钦', NULL);
INSERT INTO `student_image` VALUES ('王铭璋', NULL);
INSERT INTO `student_image` VALUES ('付佩铖', NULL);
INSERT INTO `student_image` VALUES ('吴思源', NULL);
INSERT INTO `student_image` VALUES ('汪春瑶', NULL);
INSERT INTO `student_image` VALUES ('陈杭', NULL);
INSERT INTO `student_image` VALUES ('陈鹏', NULL);
INSERT INTO `student_image` VALUES ('姜乐天', NULL);
INSERT INTO `student_image` VALUES ('徐一鸣', NULL);
INSERT INTO `student_image` VALUES ('蒋序林', NULL);
INSERT INTO `student_image` VALUES ('路超', NULL);
INSERT INTO `student_image` VALUES ('滕俊辰', NULL);
INSERT INTO `student_image` VALUES ('马静', NULL);
INSERT INTO `student_image` VALUES ('令乐乐', NULL);
INSERT INTO `student_image` VALUES ('林雨菲', NULL);
INSERT INTO `student_image` VALUES ('魏嘉怡', NULL);
INSERT INTO `student_image` VALUES ('马宇', NULL);
INSERT INTO `student_image` VALUES ('王爽', NULL);
INSERT INTO `student_image` VALUES ('庄克伟', NULL);
INSERT INTO `student_image` VALUES ('杨锐韬', NULL);
INSERT INTO `student_image` VALUES ('陈嘉春', NULL);
INSERT INTO `student_image` VALUES ('赵崇睿', NULL);
INSERT INTO `student_image` VALUES ('咸浩恒', NULL);
INSERT INTO `student_image` VALUES ('喻梓轩', NULL);
INSERT INTO `student_image` VALUES ('谭振龙', NULL);
INSERT INTO `student_image` VALUES ('赖品来', NULL);
INSERT INTO `student_image` VALUES ('肖灵', NULL);
INSERT INTO `student_image` VALUES ('吴晨', NULL);
INSERT INTO `student_image` VALUES ('张乐妍', NULL);
INSERT INTO `student_image` VALUES ('黄雨彤', NULL);
INSERT INTO `student_image` VALUES ('马沁辉', NULL);
INSERT INTO `student_image` VALUES ('邓建', NULL);
INSERT INTO `student_image` VALUES ('卢松佳', NULL);
INSERT INTO `student_image` VALUES ('吉鹏宇', NULL);
INSERT INTO `student_image` VALUES ('李予宁', NULL);
INSERT INTO `student_image` VALUES ('吴欣航', NULL);
INSERT INTO `student_image` VALUES ('邱毓诚', NULL);
INSERT INTO `student_image` VALUES ('宋东贤', NULL);
INSERT INTO `student_image` VALUES ('张嘉祥', NULL);
INSERT INTO `student_image` VALUES ('姜天浩', NULL);
INSERT INTO `student_image` VALUES ('谢俊杰', NULL);
INSERT INTO `student_image` VALUES ('王男', NULL);
INSERT INTO `student_image` VALUES ('张朝玉', NULL);
INSERT INTO `student_image` VALUES ('陈济韬', NULL);
INSERT INTO `student_image` VALUES ('夏圣宝', NULL);
INSERT INTO `student_image` VALUES ('郭飞扬', NULL);
INSERT INTO `student_image` VALUES ('曾之傲', NULL);
INSERT INTO `student_image` VALUES ('曲凯霞', NULL);
INSERT INTO `student_image` VALUES ('仲婧彬', NULL);
INSERT INTO `student_image` VALUES ('闫雪', NULL);
INSERT INTO `student_image` VALUES ('张菁菁', NULL);
INSERT INTO `student_image` VALUES ('韩承希', NULL);
INSERT INTO `student_image` VALUES ('刘靖宇', NULL);
INSERT INTO `student_image` VALUES ('杨逸岚', NULL);
INSERT INTO `student_image` VALUES ('张德贤', NULL);
INSERT INTO `student_image` VALUES ('罗钰', NULL);
INSERT INTO `student_image` VALUES ('周胜', NULL);
INSERT INTO `student_image` VALUES ('孟庆霖', NULL);
INSERT INTO `student_image` VALUES ('黄沛然', NULL);
INSERT INTO `student_image` VALUES ('田羽菲', NULL);
INSERT INTO `student_image` VALUES ('李承霖', NULL);
INSERT INTO `student_image` VALUES ('陆盈竹', NULL);
INSERT INTO `student_image` VALUES ('薛清瑶', NULL);
INSERT INTO `student_image` VALUES ('王振清', NULL);
INSERT INTO `student_image` VALUES ('孔德浩', NULL);
INSERT INTO `student_image` VALUES ('田明轩', NULL);
INSERT INTO `student_image` VALUES ('岑郅烜', NULL);
INSERT INTO `student_image` VALUES ('沈琳翔', NULL);
INSERT INTO `student_image` VALUES ('张宸宇', NULL);
INSERT INTO `student_image` VALUES ('周涛', NULL);
INSERT INTO `student_image` VALUES ('赵曜', NULL);
INSERT INTO `student_image` VALUES ('曾华扬', NULL);
INSERT INTO `student_image` VALUES ('王钰露', NULL);
INSERT INTO `student_image` VALUES ('葛杭琦', NULL);
INSERT INTO `student_image` VALUES ('马文超', NULL);
INSERT INTO `student_image` VALUES ('马洋斌', NULL);
INSERT INTO `student_image` VALUES ('朱凯', NULL);
INSERT INTO `student_image` VALUES ('刘柏均', NULL);
INSERT INTO `student_image` VALUES ('刘烔楷', NULL);
INSERT INTO `student_image` VALUES ('李佳明', NULL);
INSERT INTO `student_image` VALUES ('林梓杭', NULL);
INSERT INTO `student_image` VALUES ('柯占林', NULL);
INSERT INTO `student_image` VALUES ('黄骏骁', NULL);
INSERT INTO `student_image` VALUES ('刘芮希', NULL);
INSERT INTO `student_image` VALUES ('张惜如', NULL);
INSERT INTO `student_image` VALUES ('马子超', NULL);
INSERT INTO `student_image` VALUES ('叶泰成', NULL);
INSERT INTO `student_image` VALUES ('朱廷峰', NULL);
INSERT INTO `student_image` VALUES ('李冉', NULL);
INSERT INTO `student_image` VALUES ('张宇飏', NULL);
INSERT INTO `student_image` VALUES ('林康', NULL);
INSERT INTO `student_image` VALUES ('周潇', NULL);
INSERT INTO `student_image` VALUES ('姜富标', NULL);
INSERT INTO `student_image` VALUES ('高卓文', NULL);
INSERT INTO `student_image` VALUES ('董瑞阳', NULL);
INSERT INTO `student_image` VALUES ('张华', NULL);
INSERT INTO `student_image` VALUES ('王晓婧', NULL);
INSERT INTO `student_image` VALUES ('尹相茹', NULL);
INSERT INTO `student_image` VALUES ('代卓凡', NULL);
INSERT INTO `student_image` VALUES ('刘翀', NULL);
INSERT INTO `student_image` VALUES ('吴宏健', NULL);
INSERT INTO `student_image` VALUES ('孔羽桐', NULL);
INSERT INTO `student_image` VALUES ('李静怡', NULL);
INSERT INTO `student_image` VALUES ('邹妍妍', NULL);
INSERT INTO `student_image` VALUES ('苗瑞麟', NULL);
INSERT INTO `student_image` VALUES ('孟晓', NULL);
INSERT INTO `student_image` VALUES ('莫书迪', NULL);
INSERT INTO `student_image` VALUES ('田立新', NULL);
INSERT INTO `student_image` VALUES ('孙振宇', NULL);
INSERT INTO `student_image` VALUES ('胡顺超', NULL);
INSERT INTO `student_image` VALUES ('刘璐', NULL);
INSERT INTO `student_image` VALUES ('罗小雪', NULL);
INSERT INTO `student_image` VALUES ('李仁怀', NULL);
INSERT INTO `student_image` VALUES ('杨欣睿', NULL);
INSERT INTO `student_image` VALUES ('杨程', NULL);
INSERT INTO `student_image` VALUES ('马兰慧', NULL);
INSERT INTO `student_image` VALUES ('李沂晋', NULL);
INSERT INTO `student_image` VALUES ('龚杰', NULL);
INSERT INTO `student_image` VALUES ('李婷', NULL);
INSERT INTO `student_image` VALUES ('吴玉', NULL);
INSERT INTO `student_image` VALUES ('何璇', NULL);
INSERT INTO `student_image` VALUES ('刘天文', NULL);
INSERT INTO `student_image` VALUES ('李瑞丰', NULL);
INSERT INTO `student_image` VALUES ('吴嘉伟', NULL);
INSERT INTO `student_image` VALUES ('宋磊', NULL);
INSERT INTO `student_image` VALUES ('张尧', NULL);
INSERT INTO `student_image` VALUES ('岳毅', NULL);
INSERT INTO `student_image` VALUES ('张仁迅', NULL);
INSERT INTO `student_image` VALUES ('季筱涵', NULL);
INSERT INTO `student_image` VALUES ('王宣迪', NULL);
INSERT INTO `student_image` VALUES ('王浩', NULL);
INSERT INTO `student_image` VALUES ('朱天祥', NULL);
INSERT INTO `student_image` VALUES ('杨兴浩', NULL);
INSERT INTO `student_image` VALUES ('何芷锌', NULL);
INSERT INTO `student_image` VALUES ('宋心怡', NULL);
INSERT INTO `student_image` VALUES ('王怡欣', NULL);
INSERT INTO `student_image` VALUES ('朱灵超', NULL);
INSERT INTO `student_image` VALUES ('徐文迪', NULL);
INSERT INTO `student_image` VALUES ('王之骄', NULL);
INSERT INTO `student_image` VALUES ('冯佳楠', NULL);
INSERT INTO `student_image` VALUES ('张剑琳', NULL);
INSERT INTO `student_image` VALUES ('山宇锐', NULL);
INSERT INTO `student_image` VALUES ('王硕', NULL);
INSERT INTO `student_image` VALUES ('卞宇杰', NULL);
INSERT INTO `student_image` VALUES ('杨光辉', NULL);
INSERT INTO `student_image` VALUES ('郑明宇', NULL);
INSERT INTO `student_image` VALUES ('王宇娇', NULL);
INSERT INTO `student_image` VALUES ('李忠蔚', NULL);
INSERT INTO `student_image` VALUES ('辛政阳', NULL);
INSERT INTO `student_image` VALUES ('潘子航', NULL);
INSERT INTO `student_image` VALUES ('沈舒畅', NULL);
INSERT INTO `student_image` VALUES ('谢家明', NULL);
INSERT INTO `student_image` VALUES ('韩书星', NULL);
INSERT INTO `student_image` VALUES ('程明璐', NULL);
INSERT INTO `student_image` VALUES ('陆钊瑞', NULL);
INSERT INTO `student_image` VALUES ('李尔瀚', NULL);
INSERT INTO `student_image` VALUES ('王争', NULL);
INSERT INTO `student_image` VALUES ('毛崴', NULL);
INSERT INTO `student_image` VALUES ('刘俊杰', NULL);
INSERT INTO `student_image` VALUES ('李翔羽', NULL);
INSERT INTO `student_image` VALUES ('陈浪', NULL);
INSERT INTO `student_image` VALUES ('张佳丽', NULL);
INSERT INTO `student_image` VALUES ('王雨豪', NULL);
INSERT INTO `student_image` VALUES ('朱王令', NULL);
INSERT INTO `student_image` VALUES ('石桑俐', NULL);
INSERT INTO `student_image` VALUES ('孙思姣', NULL);
INSERT INTO `student_image` VALUES ('柏泉', NULL);
INSERT INTO `student_image` VALUES ('胡鹏飞', NULL);
INSERT INTO `student_image` VALUES ('仇扬', NULL);
INSERT INTO `student_image` VALUES ('姜斌', NULL);
INSERT INTO `student_image` VALUES ('葛彪', NULL);
INSERT INTO `student_image` VALUES ('邵如梦', NULL);
INSERT INTO `student_image` VALUES ('丁田中', NULL);
INSERT INTO `student_image` VALUES ('伍尚根', NULL);
INSERT INTO `student_image` VALUES ('闵玥', NULL);
INSERT INTO `student_image` VALUES ('张帅帅', NULL);
INSERT INTO `student_image` VALUES ('潘飞', NULL);
INSERT INTO `student_image` VALUES ('石晓彬', NULL);
INSERT INTO `student_image` VALUES ('王梦琴', NULL);
INSERT INTO `student_image` VALUES ('宋沁心', NULL);
INSERT INTO `student_image` VALUES ('向宇月', NULL);
INSERT INTO `student_image` VALUES ('吴欢华', NULL);
INSERT INTO `student_image` VALUES ('周焱', NULL);
INSERT INTO `student_image` VALUES ('李勇德', NULL);
INSERT INTO `student_image` VALUES ('刘项杰', NULL);
INSERT INTO `student_image` VALUES ('刘派', NULL);
INSERT INTO `student_image` VALUES ('刘宵宇', NULL);
INSERT INTO `student_image` VALUES ('马赛', NULL);
INSERT INTO `student_image` VALUES ('陈小朋', NULL);
INSERT INTO `student_image` VALUES ('徐剑瑜', NULL);
INSERT INTO `student_image` VALUES ('张会兴', NULL);
INSERT INTO `student_image` VALUES ('陈威', NULL);
INSERT INTO `student_image` VALUES ('姚璨', NULL);
INSERT INTO `student_image` VALUES ('钱灿辉', NULL);
INSERT INTO `student_image` VALUES ('李锦添', NULL);
INSERT INTO `student_image` VALUES ('毕欣', NULL);
INSERT INTO `student_image` VALUES ('陈一楠', NULL);
INSERT INTO `student_image` VALUES ('曹德亮', NULL);
INSERT INTO `student_image` VALUES ('张志', NULL);
INSERT INTO `student_image` VALUES ('常世琦', NULL);
INSERT INTO `student_image` VALUES ('陈亨', NULL);
INSERT INTO `student_image` VALUES ('张学妹', NULL);
INSERT INTO `student_image` VALUES ('牛兵', NULL);
INSERT INTO `student_image` VALUES ('蒋珊珊', NULL);
INSERT INTO `student_image` VALUES ('王心雨', NULL);
INSERT INTO `student_image` VALUES ('顾彦', NULL);
INSERT INTO `student_image` VALUES ('计逸宁', NULL);
INSERT INTO `student_image` VALUES ('李智彬', NULL);
INSERT INTO `student_image` VALUES ('詹进飞', NULL);
INSERT INTO `student_image` VALUES ('张荣祯', NULL);
INSERT INTO `student_image` VALUES ('张延欣', NULL);
INSERT INTO `student_image` VALUES ('黄德伟', NULL);
INSERT INTO `student_image` VALUES ('贾婧冰', NULL);
INSERT INTO `student_image` VALUES ('张美苑', NULL);
INSERT INTO `student_image` VALUES ('戴莹莹', NULL);
INSERT INTO `student_image` VALUES ('法安琪', NULL);
INSERT INTO `student_image` VALUES ('黄可言', NULL);
INSERT INTO `student_image` VALUES ('王欣', NULL);
INSERT INTO `student_image` VALUES ('俞周强', NULL);
INSERT INTO `student_image` VALUES ('张韵风', NULL);
INSERT INTO `student_image` VALUES ('曾翔', NULL);
INSERT INTO `student_image` VALUES ('孙静', NULL);
INSERT INTO `student_image` VALUES ('张仁杰', NULL);
INSERT INTO `student_image` VALUES ('张哲', NULL);
INSERT INTO `student_image` VALUES ('杜智颜', NULL);
INSERT INTO `student_image` VALUES ('冯晨晨', NULL);
INSERT INTO `student_image` VALUES ('王海燕', NULL);
INSERT INTO `student_image` VALUES ('王欣茹', NULL);
INSERT INTO `student_image` VALUES ('邹观哲', NULL);
INSERT INTO `student_image` VALUES ('高飞', NULL);
INSERT INTO `student_image` VALUES ('孟琪', NULL);
INSERT INTO `student_image` VALUES ('孙甘露', NULL);
INSERT INTO `student_image` VALUES ('谢慧慧', NULL);
INSERT INTO `student_image` VALUES ('刘玟', NULL);
INSERT INTO `student_image` VALUES ('殷秀秀', NULL);
INSERT INTO `student_image` VALUES ('张琳静', NULL);
INSERT INTO `student_image` VALUES ('张诗韵', NULL);
INSERT INTO `student_image` VALUES ('黄丽霞', NULL);
INSERT INTO `student_image` VALUES ('秦秀', NULL);
INSERT INTO `student_image` VALUES ('姚希颖', NULL);
INSERT INTO `student_image` VALUES ('尤浩杰', NULL);
INSERT INTO `student_image` VALUES ('刘南君', NULL);
INSERT INTO `student_image` VALUES ('王宪玥', NULL);
INSERT INTO `student_image` VALUES ('曾辉', NULL);

SET FOREIGN_KEY_CHECKS = 1;
